# https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

# https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    schedule:
        - cron: "0 0 * * *"

jobs:
    test:
        # https://github.com/actions/virtual-environments
        runs-on: ubuntu-latest

        strategy:
            matrix:
                # https://nodejs.org/en/about/releases/
                node-version: [14.x, 16.x]

        steps:
            # https://github.com/actions/checkout
            - uses: actions/checkout@v2

            # https://github.com/actions/setup-node
            - name: Use node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: npm

            - name: Install Dependencies
              run: npm ci

            - run: npm run lint
              env:
                  DEBUG: "*"
            #- run: npm run jest
